from sqlalchemy import String
from sqlalchemy import Column, Integer

from storage.database import Base


class Ideal(Base):
    __tablename__ = "ideal"
    __table_args__ = {'sqlite_autoincrement': True}
    ideal_id = Column(Integer, primary_key=True, autoincrement=True)
    x = Column(String)
    y1 = Column(String)
    y2 = Column(String)
    y3 = Column(String)
    y4 = Column(String)
    y5 = Column(String)
    y6 = Column(String)
    y7 = Column(String)
    y8 = Column(String)
    y9 = Column(String)
    y10 = Column(String)
    y11 = Column(String)
    y12 = Column(String)
    y13 = Column(String)
    y14 = Column(String)
    y15 = Column(String)
    y16 = Column(String)
    y17 = Column(String)
    y18 = Column(String)
    y19 = Column(String)
    y20 = Column(String)
    y21 = Column(String)
    y22 = Column(String)
    y23 = Column(String)
    y24 = Column(String)
    y25 = Column(String)
    y26 = Column(String)
    y27 = Column(String)
    y28 = Column(String)
    y29 = Column(String)
    y30 = Column(String)
    y31 = Column(String)
    y32 = Column(String)
    y33 = Column(String)
    y34 = Column(String)
    y35 = Column(String)
    y36 = Column(String)
    y37 = Column(String)
    y38 = Column(String)
    y39 = Column(String)
    y40 = Column(String)
    y41 = Column(String)
    y42 = Column(String)
    y43 = Column(String)
    y44 = Column(String)
    y45 = Column(String)
    y46 = Column(String)
    y47 = Column(String)
    y48 = Column(String)
    y49 = Column(String)
    y50 = Column(String)


